---
- name: Ensure bcg build folder not exist.
  file:
    path: "{{ rtpproxy_bcg_build_dir }}"
    state: absent

- name: Curl | get source file.
  shell: curl https://codeload.github.com/BelledonneCommunications/bcg729/tar.gz/{{ rtpproxy_bcg_version }} >bcg729_{{ rtpproxy_bcg_version }}.orig.tar.gz
  args:
    chdir: "{{ rtpproxy_working_dir }}"

- name: Extact the source.
  shell: tar zxf bcg729_{{ rtpproxy_bcg_version }}.orig.tar.gz
  args:
    chdir: "{{ rtpproxy_working_dir }}"

- name: Clone package to build bcg.
  shell: git clone https://github.com/ossobv/bcg729-deb.git debian
  args:
    chdir: "{{ rtpproxy_bcg_build_dir }}"

- name: Build bcg729 package.
  shell: dpkg-buildpackage -d -us -uc -sa
  args:
    chdir: "{{ rtpproxy_bcg_build_dir }}"

- name: Install bcg729.
  shell: dpkg -i libbcg729-*.deb
  args:
    chdir: "{{ rtpproxy_working_dir }}"